var car = "subaru";
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car === 'Subaru'? I predict False.");
console.log(car === 'Subaru');
console.log("Is car !== 'toyota'? I predict True.");
console.log(car !== 'toyota');
console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru');
console.log("Is car != 'mazda'? I predict True.");
console.log(car != 'mazda');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
var age = 25;
console.log("Is age > 18? I predict True.");
console.log(age > 18);
console.log("Is age < 21? I predict False.");
console.log(age < 21);
